# Generated by Django 3.1.5 on 2021-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210519_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='hall_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hall_id',
        ),
        migrations.AddField(
            model_name='student',
            name='hallid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
