# Generated by Django 3.1.5 on 2021-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210520_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
