# Generated by Django 3.1.2 on 2022-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220317_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
