# Generated by Django 3.1.2 on 2022-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220318_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='hallid',
            field=models.IntegerField(default=1),
        ),
    ]
