# Generated by Django 3.1.5 on 2021-05-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hall'),
        ),
    ]
