# Generated by Django 3.1.2 on 2022-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210527_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
