# Generated by Django 3.1.2 on 2022-03-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
