# Generated by Django 4.0.1 on 2022-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_messages_hallid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='id',
        ),
        migrations.AlterField(
            model_name='messages',
            name='hallid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
