# Generated by Django 4.0.1 on 2022-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_messages_id_alter_messages_hallid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='hallid',
            field=models.IntegerField(default=1),
        ),
    ]
