# Generated by Django 4.0.1 on 2022-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_messages_id_alter_messages_hallid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='hallid',
            field=models.IntegerField(default=0),
        ),
    ]
